export type GuideVisualKind =
  | 'shape' | 'footprint' | 'elevation' | 'quality' | 'smooth' | 'base'
  | 'trail' | 'fit' | 'tray' | 'pocket' | 'magnet' | 'mask' | 'mold'
  | 'sync' | 'city' | 'source' | 'paint' | 'framing'

export interface GuideVisual {
  kind: GuideVisualKind
  focus: string
  labels: [string, string]
  caption: string
}

export interface SettingGuide {
  title: string
  content: string
  tip: string
  visual: GuideVisual
}

function guide(
  title: string, kind: GuideVisualKind, focus: string, labels: [string, string],
  caption: string, content: string, tip: string,
): SettingGuide {
  return { title, content, tip, visual: { kind, focus, labels, caption } }
}

// Explicit IDs let the same setting use the same explanation in either workspace
// and in the preview editor, independently of its displayed label.
export const settingGuides = {
  shape: guide('Print shape', 'shape', '', ['Circle', 'Rectangle / polygon'], 'The outline clips the map and the printed model.', 'Choose the outline of your terrain or city print. The tray follows this shape. Pan and zoom the map to choose what fits inside it.', 'Set the shape first, then frame your route.'),
  radius: guide('Print radius', 'footprint', 'radius', ['Center', 'Print edge'], 'Radius is half the full diameter.', 'Distance from the center of a circular print to its edge, in millimeters. A 50 mm radius produces a 100 mm wide terrain or city model.', 'The Mountain tray adds a rim outside this outline.'),
  length: guide('Print length', 'footprint', 'length', ['Length ↔', 'Width ↕'], 'Length runs across the rectangular print.', 'Sets one side of the rectangular model in millimeters. This changes the physical print size; use map zoom to change the geographic area shown.', 'Check the full model and tray against your printer’s build plate.'),
  width: guide('Print width', 'footprint', 'width', ['Length ↔', 'Width ↕'], 'Width runs along the other side of the rectangle.', 'Sets the other side of the rectangular model in millimeters. Length and width together determine the print’s proportions.', 'Use map framing to keep the entire route inside the outline.'),
  sides: guide('Polygon sides', 'shape', 'sides', ['3 sides', '6 sides'], 'More sides make the outline closer to a circle.', 'Number of sides in the regular polygon. Each side has the same length. Changing the count also changes the overall footprint.', 'Recheck framing and print size after changing the side count.'),
  sideLength: guide('Polygon side length', 'footprint', 'side', ['One side', 'Equal sides'], 'The highlighted edge sets every polygon side.', 'Length of each straight side before corner rounding, in millimeters. This is an edge length, rather than the full width of the polygon.', 'A polygon’s overall width also depends on its number of sides.'),
  corner: guide('Corner radius', 'footprint', 'corner', ['Sharp corner', 'Rounded corner'], 'Larger radii soften the print’s corners.', 'Rounds the corners of rectangles and polygons. Zero keeps the corners sharp. The allowed radius depends on the size and shape of the print.', 'Small rounding can make corners easier to handle.'),
  base: guide('Base thickness', 'base', 'thickness', ['Terrain / city', 'Solid base'], 'The highlighted layer supports the model above it.', 'Thickness of the solid material beneath the terrain or city surface. Increasing it makes a sturdier model and uses more material.', 'Leave enough solid material beneath any route groove.'),
  elevation: guide('Elevation scale', 'elevation', '', ['1× elevation', 'Exaggerated'], 'Only the vertical relief is amplified.', 'Multiplies terrain elevation differences while keeping the map footprint fixed. A larger value makes hills and valleys more pronounced.', 'Use a lower value for flatter terrain; increase it to emphasize subtle relief.'),
  quality: guide('Mesh quality', 'quality', '', ['Coarse mesh', 'Fine mesh'], 'More samples follow the terrain more closely.', 'Controls how densely the elevation surface is sampled. Higher quality produces more mesh detail, larger files, and longer generation and export times.', 'A finer mesh cannot recover detail missing from the elevation dataset.'),
  grid: guide('DEM grid limit', 'quality', 'grid', ['Fewer cells', 'More cells'], 'The limit controls sampling along each grid side.', 'Sets the custom elevation grid limit per side. Increasing it creates more samples across the model; increasing both grid dimensions also increases memory use.', 'Start with a preset and increase the custom limit only when you need more detail.'),
  smoothing: guide('Terrain smoothing', 'smooth', 'terrain', ['Raw surface', 'Smoothed surface'], 'Smoothing reduces small peaks and rough edges.', 'Raw preserves the sampled elevation surface. Light, Medium, and Heavy progressively soften small irregularities in the terrain.', 'Use Raw or Light to preserve ridges; stronger smoothing also removes fine detail.'),
  dataset: guide('Elevation dataset', 'source', 'terrain', ['Elevation samples', 'Terrain model'], 'Source measurements become the model’s relief.', 'Select the elevation dataset requested from OpenTopography. Coverage and source resolution vary by dataset, so this choice limits the available terrain detail.', 'Use the dataset description to check coverage for your location.'),
  apiKey: guide('OpenTopography API key', 'source', 'key', ['Your API key', 'Elevation data'], 'The key authorizes downloads of terrain elevations.', 'Enter an OpenTopography API key to request real elevation data.', 'City’s Flat surface does not require an elevation key.'),
  simplify: guide('Smooth the trail', 'smooth', 'route', ['Recorded points', 'Cleaner route'], 'Small GPS zigzags are reduced.', 'Simplifies the GPX track and smooths small GPS irregularities before creating the trail geometry.', 'Turn it off when you need to retain the recorded route’s small turns.'),
  trailWidth: guide('Trail width', 'trail', 'width', ['Trail insert', 'Width ↔'], 'Width is measured across the trail.', 'Sets the physical width of the separate trail insert. The terrain groove also includes the clearance configured in Assembly & magnets.', 'A wider trail is easier to see and print, but covers more of the terrain.'),
  trailDepth: guide('Trail depth', 'trail', 'depth', ['Terrain surface', 'Groove depth ↕'], 'The insert seats in the terrain’s groove.', 'Controls the trail groove depth and the seated portion of the trail insert. Height above terrain adds visible relief above the fitted trail.', 'Check the preview and keep enough material below the groove.'),
  trailHeight: guide('Height above terrain', 'trail', 'relief', ['Terrain surface', 'Visible trail ↕'], 'Only the protruding part is highlighted.', 'Adds height to the trail above the terrain so the fitted insert remains visible. Zero makes it flush; increasing it creates a raised route.', 'A small positive value helps the route stand out without a tall ridge.'),
  trailClearance: guide('Trail groove clearance', 'fit', 'trail', ['Trail insert', 'Gap per side'], 'Groove width = trail width + 2 × clearance.', 'Widens the terrain groove on each side of the trail insert. The exported trail itself keeps the width set in Trail settings.', 'Increase clearance if the insert fits too tightly; test your printer’s fit on a small piece.'),
  trayClearance: guide('Base recess clearance', 'fit', 'base', ['Terrain insert', 'Recess gap'], 'Extra room surrounds the terrain in the tray.', 'Enlarges the tray recess around the terrain model so the two printed parts can fit together.', 'Larger clearance eases assembly but can allow more movement.'),
  trayThickness: guide('Tray total thickness', 'tray', 'thickness', ['Tray top', 'Tray underside'], 'Total thickness includes the recess and its floor.', 'Sets the full height of the tray from its underside to its top. The recess is cut down from the top surface.', 'Total thickness must leave a solid floor beneath the recess and any pockets.'),
  recess: guide('Tray recess depth', 'tray', 'depth', ['Recess top', 'Recess floor'], 'The terrain sits inside the recessed area.', 'How far the main terrain recess extends below the tray’s top surface. A deeper recess seats more of the model inside the tray.', 'Keep this smaller than the tray’s total thickness.'),
  rim: guide('Tray rim width', 'tray', 'rim', ['Terrain recess', 'Outer rim'], 'The border extends beyond the model recess.', 'Width of the tray border surrounding the terrain recess. Increasing it enlarges the tray’s outer footprint.', 'Include the rim when checking the finished print against your build plate.'),
  nfc: guide('NFC & LED indicators', 'pocket', 'enabled', ['NFC recess', 'LED pockets'], 'Pockets hold electronics under a separate cover.', 'Adds a recess for an NFC chip and LED pockets at the route start and end. The export also includes a matching assembly cover with light openings.', 'Enable this when you plan to install an NFC chip and LEDs.'),
  nfcInset: guide('NFC recess inset', 'pocket', 'inset', ['Print outline', 'Inset recess'], 'The recess shrinks inward from the print edge.', 'Distance from the terrain print outline to the NFC recess boundary. The recess keeps the print’s shape and center.', 'Larger inset leaves more material around the electronics recess.'),
  nfcDepth: guide('NFC recess depth', 'pocket', 'depth', ['Recess surface', 'Chip pocket ↕'], 'The chip pocket sits below the main recess surface.', 'Depth of the NFC recess below the tray’s main recess surface. This creates space for the chip under the assembly cover.', 'Allow for the chip thickness while retaining a solid tray floor.'),
  ledLength: guide('LED pocket length', 'pocket', 'length', ['Along the route ↔', 'LED pocket'], 'The long edge follows the route direction.', 'Length of each rectangular LED pocket at the GPX start and end. Extra space can accommodate the LED and its connections.', 'Size the pocket for the LED package and your wiring.'),
  ledWidth: guide('LED pocket width', 'pocket', 'width', ['Across the route ↕', 'LED pocket'], 'Width is measured across each rectangular pocket.', 'Width of the LED pockets at the trail start and end, measured across the route direction.', 'Leave room for assembly without making the pockets unnecessarily large.'),
  ledDepth: guide('Extra LED depth', 'pocket', 'extraDepth', ['NFC pocket floor', 'LED pocket floor'], 'The LED sits deeper than the NFC chip.', 'Additional depth of the LED pockets below the NFC recess floor. Zero puts them at the same depth as the NFC recess.', 'Check the remaining tray floor before adding more depth.'),
  coverThickness: guide('Cover thickness', 'pocket', 'cover', ['Assembly cover', 'Electronics below'], 'A separate thin cover closes the electronics recess.', 'Thickness of the exported Tray_Cover.stl part over the NFC chip and LEDs. Light openings align with the route start and end.', 'Choose a thickness your printer can produce reliably.'),
  coverInset: guide('Cover inset', 'fit', 'cover', ['Cover outline', 'Fit gap'], 'The cover is slightly smaller than the terrain outline.', 'Shrinks the assembly cover inward from the terrain outline while preserving its shape and center.', 'A small inset helps the cover fit into the recess.'),
  magnets: guide('Underside magnet holes', 'magnet', 'layout', ['Underside view', 'Magnet holes'], 'Holes open on the bottom of the tray.', 'Adds pockets with the selected magnet shape and dimensions. Rectangular and polygonal trays place them at corners; circular trays space them around the perimeter.', 'Match the dimensions to the magnets you intend to install.'),
  magnetShape: guide('Magnet hole shape', 'magnet', 'shape', ['Round / rectangle', 'Hexagon'], 'Pocket shape is independent of the map outline.', 'Choose a round, rectangular or hexagonal magnet pocket. A square magnet uses Rectangle with equal length and width.', 'Enter the actual magnet dimensions; clearance is added separately.'),
  magnetLength: guide('Magnet length', 'magnet', 'length', ['Rectangular magnet', 'Length ↔'], 'Length measures along the longer side.', 'Nominal length of a rectangular magnet. The pocket adds twice the configured clearance to this dimension.', 'Use equal length and width for square magnets.'),
  magnetWidth: guide('Magnet width', 'magnet', 'width', ['Rectangular magnet', 'Width ↕'], 'Width measures across the other side.', 'Nominal width of a rectangular magnet. The pocket adds twice the configured clearance to this dimension.', 'Measure both dimensions before selecting the pocket size.'),
  magnetAcrossFlats: guide('Magnet width across flats', 'magnet', 'acrossFlats', ['Hexagonal magnet', 'Opposite flat faces'], 'Measure between two opposite flat faces.', 'Nominal width across flats of a hexagonal magnet. Clearance expands the pocket on all sides.', 'Measure between flat faces rather than between corners.'),
  magnetDiameter: guide('Magnet diameter', 'magnet', 'diameter', ['Round magnet', 'Round pocket'], 'Diameter measures across the round magnet.', 'Nominal diameter of your round magnet. The round pocket surrounds the magnet, with extra space added by Magnet hole clearance.', 'Measure the actual magnet before selecting pocket dimensions.'),
  magnetThickness: guide('Magnet thickness', 'magnet', 'depth', ['Tray underside', 'Pocket depth ↕'], 'The pocket depth follows the magnet thickness.', 'Nominal thickness of the magnet. The cut depth includes this thickness plus the configured hole clearance.', 'Leave material above the hole so it does not break into the terrain recess.'),
  magnetClearance: guide('Magnet hole clearance', 'magnet', 'clearance', ['Magnet', 'Extra fit space'], 'Clearance increases the pocket size and depth.', 'Adds clearance around the magnet and below it. Diameter, across-flats width or rectangle dimensions grow by twice this value; depth grows by this value.', 'Increase in small steps if your printer produces a tight fit.'),
  magnetCount: guide('Magnet hole count', 'magnet', 'layout', ['Fewer holes', 'More support points'], 'Circular trays space the holes evenly around the underside.', 'Number of magnet pockets around a circular tray. Rectangle and polygon hole counts follow their corners instead.', 'Balance holding force with space between holes and the tray’s edge.'),
  paintMasks: guide('Enable paint masks', 'mask', 'enabled', ['Terrain', 'Separate paint mask'], 'Each mask exposes the region you want to paint.', 'Adds printable masks for the color regions assigned in the 3D preview. Generate the masks in the preview before downloading them with the model.', 'Use the preview to assign colors and inspect mask fit.'),
  maskThickness: guide('Mask thickness', 'mask', 'thickness', ['Terrain', 'Mask shell ↕'], 'A thicker shell produces a sturdier mask.', 'Thickness of the printable paint-mask shell above the model. More thickness makes the mask more rigid and uses more material.', 'Use enough thickness for handling and repeated painting.'),
  maskClearance: guide('Mask fit clearance', 'mask', 'clearance', ['Terrain surface', 'Mask gap ↕'], 'A small gap separates the mask from the terrain.', 'Offsets the mask above the terrain surface to make it easier to fit and remove.', 'Too much clearance can let paint reach under the mask; inspect the fit preview.'),
  overlap: guide('Edge overlap', 'mask', 'overlap', ['Color boundary', 'Mask overlap'], 'The mask extends across the neighboring region’s edge.', 'Expands the protected mask area around color-region boundaries to reduce paint bleeding at their edges.', 'More overlap protects edges but can leave a narrower exposed paint area.'),
  mold: guide('Enable mold kit', 'mold', 'enabled', ['Terrain master', 'Casting lid'], 'Extra parts help create a silicone mold and resin casts.', 'Exports a terrain master with an overflow skirt and a casting lid with raised grips, alongside the normal model parts.', 'Pour resin to the original base step; the skirt catches overflow.'),
  skirtHeight: guide('Skirt height', 'mold', 'height', ['Terrain master', 'Skirt height ↕'], 'The skirt rises around the terrain master.', 'Height of the solid overflow skirt surrounding the terrain master. It catches excess resin during casting.', 'When Match skirt dimensions is on, this also sets the lid height.'),
  skirtWidth: guide('Skirt extension', 'mold', 'width', ['Terrain outline', 'Skirt extension ↔'], 'The skirt extends outward from the terrain outline.', 'How far the overflow skirt extends beyond the terrain master’s footprint on each side.', 'Allow room around the model for overflow and handling.'),
  sync: guide('Match skirt dimensions', 'sync', '', ['Skirt dimensions', 'Lid dimensions'], 'Linked values update together.', 'Automatically copies skirt height and extension to the lid. The lid fields stay locked while this is enabled.', 'Turn this off to choose the lid dimensions independently.'),
  lidHeight: guide('Lid height', 'mold', 'lidHeight', ['Casting lid', 'Lid height ↕'], 'Height sets the body thickness of the casting lid.', 'Height of the casting lid’s main body. Raised grips are added above it for handling and weighting.', 'Turn off Match skirt dimensions to edit this value.'),
  lidWidth: guide('Lid extension', 'mold', 'lidWidth', ['Terrain outline', 'Lid extension ↔'], 'The lid extends past the original terrain footprint.', 'Outward extension of the casting lid. Lid fit clearance is subtracted from this extension to determine the final outline.', 'The lid extension must be larger than its fit clearance.'),
  lidClearance: guide('Lid fit clearance', 'fit', 'lid', ['Lid outline', 'Reduced extension'], 'Final lid extension = lid extension − clearance.', 'Reduces the casting lid’s outer extension to give it room to fit. It does not change the skirt dimensions.', 'Increase slightly for easier insertion; keep it below the lid extension.'),
  surface: guide('City surface', 'elevation', 'city', ['Flat city base', 'Real terrain'], 'Choose a level base or one that follows local elevation.', 'Flat builds a level city model using map data. Real terrain places the city on an elevation surface and requires an OpenTopography API key.', 'Try Flat for a simple city print; choose Real terrain to include hills.'),
  buildings: guide('Show buildings', 'city', 'buildings', ['Buildings hidden', 'Buildings shown'], 'Building footprints become raised blocks.', 'Includes mapped OpenStreetMap buildings in the city model. Heights use mapped height, building levels, or a fallback when neither is available.', 'Missing buildings in the source map cannot appear in the print.'),
  buildingHeight: guide('Building height exaggeration', 'city', 'height', ['Original heights', 'Scaled heights'], 'Only building heights are multiplied.', 'Multiplies the modeled building heights while keeping their footprints fixed. A larger value makes the skyline more pronounced.', 'Lower values can help small buildings print as sturdier blocks.'),
  roads: guide('Show roads & footpaths', 'city', 'roads', ['Roads hidden', 'Roads shown'], 'Mapped paths appear as raised strips.', 'Includes mapped roads and footpaths on the city surface. The running route keeps its own insert and clearance.', 'Turn this off for a simpler model focused on buildings and your route.'),
  roadRelief: guide('Raised roads', 'city', 'relief', ['City surface', 'Road relief ↕'], 'Relief sets how far roads rise above the surface.', 'Height of the raised road and footpath geometry above the city surface, in millimeters.', 'Use a small relief to distinguish roads without overpowering the running route.'),
  routeWidth: guide('Route width', 'trail', 'width', ['Route insert', 'Width ↔'], 'The separate route insert fits into the city base.', 'Physical width of the running-route insert. Its groove is widened by the Clearance per side setting.', 'A wider insert is easier to see, but covers more city detail.'),
  routeClearance: guide('Clearance per side', 'fit', 'trail', ['Route insert', 'Gap per side'], 'Groove width = route width + 2 × clearance.', 'Extra space on each side of the route insert inside its groove. Buildings and roads also leave room around the route.', 'Increase slightly if the printed route is difficult to seat.'),
  routeDepth: guide('Seating depth', 'trail', 'depth', ['City surface', 'Seated route ↕'], 'The lower part of the route seats inside the city base.', 'Depth of the route groove below the city surface. The route insert also includes the height set by Visible route relief.', 'Keep at least 0.4 mm of base material below the groove.'),
  routeRelief: guide('Visible route relief', 'trail', 'relief', ['City surface', 'Visible route ↕'], 'This is the route height above the city surface.', 'Height of the route insert above the city surface after it is seated in the groove.', 'Increase it to emphasize your run against the city layers.'),
  brush: guide('Paint brush size', 'paint', 'brush', ['Small brush', 'Large brush'], 'A larger brush assigns more terrain cells per stroke.', 'Changes the radius of the manual paint brush. Select a palette color, then click and drag over the terrain to assign cells to its region.', 'Use a small brush for boundaries and a larger brush to fill broad areas.'),
  palette: guide('Paint palette', 'paint', 'palette', ['Color regions', 'One mask per region'], 'Palette colors identify the regions used to make masks.', 'Select a swatch to paint its region. Double-click it to change its display color. Adding or removing a color changes the available regions.', 'Regenerate masks after changing the region assignments.'),
  maskView: guide('Mask fit preview', 'mask', 'view', ['Fitted mask', 'Lifted mask'], 'Preview modes help inspect how a mask meets the terrain.', 'Switch the mask display mode and show or hide individual masks to inspect fit and protected areas on the model.', 'These display controls affect the preview, not the exported mask dimensions.'),
  presetName: guide('Preset name', 'framing', 'preset', ['Current settings', 'Saved preset'], 'A preset stores settings for reuse on another track.', 'Names a saved collection of model settings. Presets exclude GPX track data and your OpenTopography API key.', 'Choose a name that describes the print size or use.'),
  saveFraming: guide('Save map coordinates and framing', 'framing', '', ['Current framing', 'Restored framing'], 'Location, zoom, and rotation can travel with a preset.', 'Includes the map position, zoom, and rotation in the preset. Applying it restores this framing along with the model settings.', 'Leave this off when reusing the model settings in a different location.'),
  positioning: guide('Positioning grid', 'framing', 'grid', ['Grid off', 'Grid on'], 'Reference lines help align the route inside the print outline.', 'Shows a grid over the map for positioning your track. The white outline is the terrain print, and the yellow outline includes the tray.', 'The grid is a framing aid and does not add lines to the exported model.'),
} satisfies Record<string, SettingGuide>

export type SettingGuideId = keyof typeof settingGuides
